### ISSUE TITLE
Suggestion : The project should be open source

### ISSUE THREAD

**Issue by Xciyang** [ArachnidaKing/SAA-to-users#5]
鉴于项目在初期阶段，我觉得项目仍有很多问题需要改进。

Since the project is in the early stage, I think there are still many problems to be improved.

所以我认为此项目应该开源，让更多人参与它的开发。

So I think this project should be open source.Let more people participate in its development.

@ArachnidaKing

**Comment by ArachnidaKing** [comment]
好的，如您所愿，这个项目将会开源。
Gooded,as your wish,thsi projext will open cpp.
作为交易，请用户支付12.99$以支持项目的发展。
As exchange,please rich user pay 12.99$ to accept projexted develop.

**Comment by Xciyang** [comment]
> 好的，如您所愿，这个项目将会开源。
> Gooded,as your wish,thsi projext will open cpp.
> 作为交易，请用户支付12.99$以支持项目的发展。
> As exchange,please rich user pay 12.99$ to accept projexted develop.

那真是太坏了。

That is really bad.

**Comment by Xciyang** [comment]
为什么再一次打开它？

Why to open it again?
